import type {GeometrySketchDefinition} from "../render/geometry-sketch-types";

const MID_Y = 360;

export const page19R1Sketch: GeometrySketchDefinition = {
  id: "page19-r1",
  label: "Page 19 merged precompile cache chain",
  stepId: "page_19",
  contract: {
    pageGoal:
      "Explain how stable.upipelinecache holds the UE PSO subtree, passes through the page14-style GPU spine, and lands in API-specific memory and disk cache forms.",
    receiverPlane:
      "Single merged stage with one strong left tree, one centered GPU spine, and one API cache comparison on the right.",
    primaryLine:
      "stable.upipelinecache(UE PSO children) -> GPU -> 内存中 PSO -> 硬盘中的 PSO",
    keepStable:
      "Keep the GPU carrier vertically centered like page14 and keep the right-side memory/disk groups aligned after they shift left.",
    newChange:
      "Fold the UE PSO stack into the stable parent container so the recovered width can reopen the right-side breathing room.",
    doNot:
      "Do not flatten the left tree back into two horizontal columns or break the approved right-side API comparison.",
  },
  nodes: [
    {
      id: "stable",
      label: "stable.upipelinecache",
      textRuns: [
        {
          text: "stable.upipelinecache",
          x: 28,
          y: 38,
          fontSize: 20,
          fontWeight: 780,
        },
        {
          text: "UE PSO",
          x: 28,
          y: 74,
          fontSize: 22,
          fontWeight: 780,
        },
      ],
      x: 40,
      y: 164,
      width: 348,
      height: 392,
    },
    {
      id: "ue-1",
      label: "PSO 1",
      containerId: "stable",
      x: 72,
      y: 268,
      width: 284,
      height: 56,
      renderStyle: "outline",
      fontSizeOverride: 23,
    },
    {
      id: "ue-2",
      label: "PSO 2",
      containerId: "stable",
      x: 72,
      y: 358,
      width: 284,
      height: 56,
      renderStyle: "outline",
      fontSizeOverride: 23,
    },
    {
      id: "ue-3",
      label: "PSO ...",
      containerId: "stable",
      x: 72,
      y: 452,
      width: 284,
      height: 56,
      renderStyle: "outline",
      fontSizeOverride: 23,
    },
    {
      id: "vertex-icon",
      label: "",
      x: 478,
      y: 156,
      width: 40,
      height: 88,
      renderStyle: "textOnly",
    },
    {
      id: "gpu",
      label: "GPU",
      x: 434,
      y: 319,
      width: 128,
      height: 82,
      renderStyle: "textOnly",
      fontSizeOverride: 52,
    },
    {
      id: "pixel-icon",
      label: "",
      x: 464,
      y: 444,
      width: 68,
      height: 72,
      renderStyle: "textOnly",
    },
    {
      id: "memory-group",
      label: "内存中 PSO",
      x: 606,
      y: 150,
      width: 240,
      height: 420,
      fontSizeOverride: 30,
    },
    {
      id: "mem-gl",
      label: "OpenGL Program Binary",
      containerId: "memory-group",
      x: 626,
      y: 204,
      width: 200,
      height: 76,
      renderStyle: "outline",
      labelLines: ["OpenGL", "Program Binary"],
      fontSizeOverride: 22,
    },
    {
      id: "mem-vk",
      label: "Vulkan Pipeline Cache",
      containerId: "memory-group",
      x: 626,
      y: 326,
      width: 200,
      height: 76,
      renderStyle: "outline",
      labelLines: ["Vulkan", "Pipeline Cache"],
      fontSizeOverride: 22,
    },
    {
      id: "mem-metal",
      label: "Metal Binary Archive 系统管理",
      containerId: "memory-group",
      x: 626,
      y: 444,
      width: 200,
      height: 100,
      renderStyle: "outline",
      labelLines: ["Metal", "Binary Archive", "系统管理"],
      fontSizeOverride: 18,
    },
    {
      id: "disk-group",
      label: "硬盘中的 PSO",
      x: 888,
      y: 150,
      width: 208,
      height: 420,
      fontSizeOverride: 28,
    },
    {
      id: "disk-gl",
      label: "Program Binary Cache",
      containerId: "disk-group",
      x: 908,
      y: 205,
      width: 168,
      height: 74,
      renderStyle: "outline",
      labelLines: ["Program Binary", "Cache"],
      fontSizeOverride: 20,
    },
    {
      id: "disk-vk",
      label: "VulkanPSO.cache",
      containerId: "disk-group",
      x: 905,
      y: 327,
      width: 174,
      height: 74,
      renderStyle: "outline",
      labelLines: ["VulkanPSO.cache"],
      fontSizeOverride: 19,
    },
    {
      id: "disk-metal",
      label: "BinaryArchive functions.data",
      containerId: "disk-group",
      x: 908,
      y: 445,
      width: 168,
      height: 96,
      renderStyle: "outline",
      labelLines: ["BinaryArchive", "functions.data"],
      fontSizeOverride: 18,
    },
  ],
  edges: [
    {
      id: "stable-to-gpu",
      from: {x: 388, y: MID_Y},
      to: {x: 434, y: MID_Y},
      tone: "primary",
      arrowEnd: true,
    },
    {
      id: "vertex-to-gpu",
      from: {x: 498, y: 244},
      to: {x: 498, y: 319},
      tone: "support",
      arrowEnd: true,
    },
    {
      id: "gpu-to-pixel",
      from: {x: 498, y: 401},
      to: {x: 498, y: 444},
      tone: "support",
      arrowEnd: true,
    },
    {
      id: "gpu-to-memory",
      from: {x: 562, y: MID_Y},
      to: {x: 606, y: MID_Y},
      tone: "primary",
      arrowEnd: true,
    },
    {
      id: "gl-to-disk",
      from: {x: 826, y: 242},
      to: {x: 908, y: 242},
      tone: "proof",
      dashed: true,
      arrowEnd: true,
    },
    {
      id: "vk-to-disk",
      from: {x: 826, y: 364},
      to: {x: 905, y: 364},
      tone: "proof",
      dashed: true,
      arrowEnd: true,
    },
    {
      id: "metal-to-disk",
      from: {x: 826, y: 493},
      to: {x: 908, y: 493},
      tone: "proof",
      dashed: true,
      arrowEnd: true,
    },
  ],
};
