import {
  PAGE8_MATERIAL_BOX,
  PAGE8_PSO_BOX,
  PAGE8_RESOURCE_BOX,
  PAGE8_SHADERMAP_BOX,
  PAGE9_FSHADER_BOX,
  PAGE9_CODE_BOX,
  PAGE9_HASHES_BOX,
  PAGE9_LIBRARY_BOX,
  PAGE9_SHADERMAP_ENTRIES_BOX,
  PAGE9_SHARED_RESOURCE_BOX,
  PAGE9_UASSET_FRAME,
} from "../../../remotion/pages/page-layout-constants";
import type {GeometrySketchDefinition} from "../render/geometry-sketch-types";

const PAGE9_LOOKUP_EXPR_BOX = {
  x: PAGE9_SHADERMAP_ENTRIES_BOX.x,
  y: 204,
  width: PAGE9_SHADERMAP_ENTRIES_BOX.width,
  height: 60,
};

const PAGE9_LIBRARY_INDEX_BOX = {
  x: PAGE9_HASHES_BOX.x,
  y: 204,
  width:
    PAGE9_CODE_BOX.x +
    PAGE9_CODE_BOX.width -
    PAGE9_HASHES_BOX.x,
  height: 60,
};

const PAGE9_CODE_SLICE_BOX = {
  x: PAGE9_CODE_BOX.x,
  y: PAGE9_CODE_BOX.y + PAGE9_CODE_BOX.height + 8,
  width: PAGE9_CODE_BOX.width,
  height: 92,
};

const SHARED_RESOURCE_PILL_WIDTH = 176;
const SHARED_RESOURCE_PILL_HEIGHT = 30;
const SHARED_RESOURCE_PILL_X =
  PAGE9_SHARED_RESOURCE_BOX.x +
  (PAGE9_SHARED_RESOURCE_BOX.width - SHARED_RESOURCE_PILL_WIDTH) / 2;

export const page09R1Sketch: GeometrySketchDefinition = {
  id: "page09-r1",
  label: "SharedCode page09 mirror sketch",
  stepId: "page_09",
  contract: {
    pageGoal: "Mirror the real page09 structure before simplifying geometry.",
    receiverPlane: "SharedCode Library",
    primaryLine:
      "FShader / ShaderMapIndex / Hash -> LibraryShaderIndex -> ShaderEntries -> Cooked ShaderCode",
    keepStable: "Keep the lower PSO cache band separated from the SharedCode lookup block.",
    newChange: "Mirror the finished page09 topology instead of inventing a generic demo layout.",
    doNot: "Do not collapse the real lookup chain into a fake three-box summary.",
  },
  nodes: [
    {
      id: "uasset",
      label: "uasset",
      x: PAGE9_UASSET_FRAME.x,
      y: PAGE9_UASSET_FRAME.y,
      width: PAGE9_UASSET_FRAME.width,
      height: PAGE9_UASSET_FRAME.height,
      tone: "muted",
    },
    {
      id: "material",
      label: "Material",
      containerId: "uasset",
      x: PAGE8_MATERIAL_BOX.x,
      y: PAGE8_MATERIAL_BOX.y,
      width: PAGE8_MATERIAL_BOX.width,
      height: PAGE8_MATERIAL_BOX.height,
      tone: "muted",
    },
    {
      id: "resource",
      label: "FMaterialResource",
      containerId: "uasset",
      x: PAGE8_RESOURCE_BOX.x,
      y: PAGE8_RESOURCE_BOX.y,
      width: PAGE8_RESOURCE_BOX.width,
      height: PAGE8_RESOURCE_BOX.height,
      tone: "muted",
    },
    {
      id: "shadermap",
      label: "FMaterialShaderMap",
      containerId: "uasset",
      x: PAGE8_SHADERMAP_BOX.x,
      y: PAGE8_SHADERMAP_BOX.y,
      width: PAGE8_SHADERMAP_BOX.width,
      height: PAGE8_SHADERMAP_BOX.height,
      tone: "muted",
    },
    {
      id: "fshader",
      label: "FShader",
      containerId: "uasset",
      x: PAGE9_FSHADER_BOX.x,
      y: PAGE9_FSHADER_BOX.y,
      width: PAGE9_FSHADER_BOX.width,
      height: PAGE9_FSHADER_BOX.height,
    },
    {
      id: "shared-resource",
      label: "FShaderMapResource_SharedCode",
      containerId: "uasset",
      x: PAGE9_SHARED_RESOURCE_BOX.x,
      y: PAGE9_SHARED_RESOURCE_BOX.y,
      width: PAGE9_SHARED_RESOURCE_BOX.width,
      height: PAGE9_SHARED_RESOURCE_BOX.height,
      tone: "receiver",
    },
    {
      id: "resource-index",
      label: "ResourceIndex",
      containerId: "shared-resource",
      x: SHARED_RESOURCE_PILL_X,
      y: PAGE9_SHARED_RESOURCE_BOX.y + 16,
      width: SHARED_RESOURCE_PILL_WIDTH,
      height: SHARED_RESOURCE_PILL_HEIGHT,
    },
    {
      id: "shadermap-index",
      label: "ShaderMapIndex",
      containerId: "shared-resource",
      x: SHARED_RESOURCE_PILL_X,
      y: PAGE9_SHARED_RESOURCE_BOX.y + 52,
      width: SHARED_RESOURCE_PILL_WIDTH,
      height: SHARED_RESOURCE_PILL_HEIGHT,
    },
    {
      id: "library",
      label: "SharedCode Library",
      x: PAGE9_LIBRARY_BOX.x,
      y: PAGE9_LIBRARY_BOX.y,
      width: PAGE9_LIBRARY_BOX.width,
      height: PAGE9_LIBRARY_BOX.height,
      tone: "receiver",
    },
    {
      id: "lookup-formula",
      label: "ShaderIndices",
      containerId: "library",
      x: PAGE9_LOOKUP_EXPR_BOX.x,
      y: PAGE9_LOOKUP_EXPR_BOX.y,
      width: PAGE9_LOOKUP_EXPR_BOX.width,
      height: PAGE9_LOOKUP_EXPR_BOX.height,
    },
    {
      id: "library-index",
      label: "LibraryShaderIndex",
      containerId: "library",
      x: PAGE9_LIBRARY_INDEX_BOX.x,
      y: PAGE9_LIBRARY_INDEX_BOX.y,
      width: PAGE9_LIBRARY_INDEX_BOX.width,
      height: PAGE9_LIBRARY_INDEX_BOX.height,
      tone: "receiver",
    },
    {
      id: "entries",
      label: "ShaderMapEntries",
      containerId: "library",
      x: PAGE9_SHADERMAP_ENTRIES_BOX.x,
      y: PAGE9_SHADERMAP_ENTRIES_BOX.y,
      width: PAGE9_SHADERMAP_ENTRIES_BOX.width,
      height: PAGE9_SHADERMAP_ENTRIES_BOX.height,
    },
    {
      id: "hashes",
      label: "ShaderHashTable",
      containerId: "library",
      x: PAGE9_HASHES_BOX.x,
      y: PAGE9_HASHES_BOX.y,
      width: PAGE9_HASHES_BOX.width,
      height: PAGE9_HASHES_BOX.height,
    },
    {
      id: "code",
      label: "ShaderEntries",
      containerId: "library",
      x: PAGE9_CODE_BOX.x,
      y: PAGE9_CODE_BOX.y,
      width: PAGE9_CODE_BOX.width,
      height: PAGE9_CODE_BOX.height,
    },
    {
      id: "blob",
      label: "Cooked ShaderCode",
      containerId: "library",
      x: PAGE9_CODE_SLICE_BOX.x,
      y: PAGE9_CODE_SLICE_BOX.y,
      width: PAGE9_CODE_SLICE_BOX.width,
      height: PAGE9_CODE_SLICE_BOX.height,
    },
    {
      id: "pso-cache",
      label: "PSO Cache",
      x: PAGE8_PSO_BOX.x,
      y: PAGE8_PSO_BOX.y,
      width: PAGE8_PSO_BOX.width,
      height: PAGE8_PSO_BOX.height,
      tone: "muted",
    },
  ],
  edges: [
    {
      id: "shadermap-to-shared",
      from: {x: 186, y: 432},
      to: {x: 296, y: 458},
      waypoints: [{x: 186, y: 458}],
      tone: "support",
    },
    {
      id: "resourceindex-to-lookup",
      from: {x: SHARED_RESOURCE_PILL_X + SHARED_RESOURCE_PILL_WIDTH, y: 441},
      to: {x: PAGE9_LOOKUP_EXPR_BOX.x, y: 234},
      waypoints: [{x: 584, y: 441}, {x: 584, y: 234}],
      tone: "primary",
      dashed: true,
    },
    {
      id: "shadermapindex-to-entries",
      from: {x: SHARED_RESOURCE_PILL_X + SHARED_RESOURCE_PILL_WIDTH, y: 477},
      to: {x: PAGE9_SHADERMAP_ENTRIES_BOX.x, y: 477},
      tone: "primary",
      dashed: true,
    },
    {
      id: "fshader-to-lookup",
      from: {x: PAGE9_FSHADER_BOX.x + PAGE9_FSHADER_BOX.width, y: 234},
      to: {x: PAGE9_LOOKUP_EXPR_BOX.x, y: 234},
      waypoints: [{x: 584, y: 234}],
      tone: "support",
      dashed: true,
    },
    {
      id: "lookup-to-library-index",
      from: {x: PAGE9_LOOKUP_EXPR_BOX.x + PAGE9_LOOKUP_EXPR_BOX.width, y: 234},
      to: {x: PAGE9_LIBRARY_INDEX_BOX.x, y: 234},
      tone: "primary",
    },
    {
      id: "hash-to-library-index",
      from: {x: 926, y: 316},
      to: {x: 926, y: 264},
      tone: "proof",
    },
    {
      id: "library-index-to-entries",
      from: {x: 724, y: 264},
      to: {x: 724, y: 316},
      tone: "support",
    },
    {
      id: "library-index-to-code",
      from: {x: 1105, y: 264},
      to: {x: 1105, y: 316},
      tone: "primary",
    },
    {
      id: "code-to-blob",
      from: {x: 1105, y: 408},
      to: {x: 1105, y: 416},
      tone: "primary",
    },
    {
      id: "pso-to-hash",
      from: {x: 926, y: 590},
      to: {x: 926, y: 504},
      tone: "proof",
      dashed: true,
    },
  ],
};
