import type {GeometrySketchDefinition} from "../render/geometry-sketch-types";

const MID_Y = 360;

export const page19R1Sketch: GeometrySketchDefinition = {
  id: "page19-r1",
  label: "Page 19 merged precompile cache chain",
  stepId: "page_19",
  contract: {
    pageGoal:
      "Explain how stable.upipelinecache expands into the UE PSO subtree, converges into a GfxPSO in memory, drives the top horizontal GPU strip, and branches into API-specific binary/cache forms plus disk persistence.",
    receiverPlane:
      "Single merged stage with one strong left tree, one top horizontal GPU strip, one centered GfxPSO pivot, one right-side API/disk comparison, and a three-note binary boundary row at the bottom.",
    primaryLine:
      "stable.upipelinecache(UE PSO children) -> GfxPSO -> GPU strip + API cache forms -> 硬盘中的 PSO",
    keepStable:
      "Keep the left stable tree strong, keep VertexData / GPU / Pixels horizontal above GfxPSO, and keep the API and disk columns vertically aligned.",
    newChange:
      "Replace the old 内存中 PSO container with a single GfxPSO card, route it upward into GPU, and move the GPU three into one top row.",
    doNot:
      "Do not restore the old vertical GPU spine and do not call the API comparison group 内存中 PSO again.",
  },
  nodes: [
    {
      id: "stable",
      label: "stable.upipelinecache",
      textRuns: [
        {
          text: "UE PSO",
          x: 162,
          y: 42,
          fontSize: 34,
          fontWeight: 820,
          textAnchor: "middle",
        },
        {
          text: "stable.upipelinecache",
          x: 162,
          y: 78,
          fontSize: 18,
          fontWeight: 760,
          textAnchor: "middle",
        },
      ],
      x: 108,
      y: 164,
      width: 324,
      height: 392,
    },
    {
      id: "ue-1",
      label: "PSO 1",
      containerId: "stable",
      x: 130,
      y: 268,
      width: 280,
      height: 56,
      renderStyle: "outline",
      fontSizeOverride: 23,
    },
    {
      id: "ue-2",
      label: "PSO 2",
      containerId: "stable",
      x: 130,
      y: 360,
      width: 280,
      height: 56,
      renderStyle: "outline",
      fontSizeOverride: 23,
    },
    {
      id: "ue-3",
      label: "PSO ...",
      containerId: "stable",
      x: 130,
      y: 452,
      width: 280,
      height: 56,
      renderStyle: "outline",
      fontSizeOverride: 23,
    },
    {
      id: "vertex-icon",
      label: "",
      x: 402,
      y: 34,
      width: 88,
      height: 88,
      renderStyle: "textOnly",
    },
    {
      id: "gpu",
      label: "GPU",
      x: 582,
      y: 38,
      width: 116,
      height: 80,
      renderStyle: "textOnly",
      fontSizeOverride: 52,
    },
    {
      id: "pixel-icon",
      label: "",
      x: 790,
      y: 40,
      width: 68,
      height: 76,
      renderStyle: "textOnly",
    },
    {
      id: "gfx-pso",
      label: "GfxPSO",
      x: 478,
      y: 164,
      width: 324,
      height: 392,
      fontSizeOverride: 30,
    },
    {
      id: "api-gl",
      label: "OpenGL Program Binary",
      containerId: "gfx-pso",
      x: 500,
      y: 218,
      width: 280,
      height: 70,
      renderStyle: "outline",
      labelLines: ["OpenGL", "Program Binary"],
      fontSizeOverride: 22,
    },
    {
      id: "api-vk",
      label: "Vulkan Pipeline Cache",
      containerId: "gfx-pso",
      x: 500,
      y: 326,
      width: 280,
      height: 70,
      renderStyle: "outline",
      labelLines: ["Vulkan", "Pipeline Cache"],
      fontSizeOverride: 22,
    },
    {
      id: "api-metal",
      label: "Metal Binary Archive 系统管理",
      containerId: "gfx-pso",
      x: 500,
      y: 434,
      width: 280,
      height: 70,
      renderStyle: "outline",
      labelLines: ["Metal", "Binary Archive", "系统管理"],
      fontSizeOverride: 17,
    },
    {
      id: "disk-group",
      label: "硬盘中的 PSO",
      x: 848,
      y: 164,
      width: 324,
      height: 392,
      fontSizeOverride: 28,
    },
    {
      id: "disk-gl",
      label: "Program Binary Cache",
      containerId: "disk-group",
      x: 870,
      y: 218,
      width: 280,
      height: 70,
      renderStyle: "outline",
      labelLines: ["Program Binary", "Cache"],
      fontSizeOverride: 18,
    },
    {
      id: "disk-vk",
      label: "VulkanPSO.cache",
      containerId: "disk-group",
      x: 870,
      y: 326,
      width: 280,
      height: 70,
      renderStyle: "outline",
      labelLines: ["VulkanPSO.cache"],
      fontSizeOverride: 18,
    },
    {
      id: "disk-metal",
      label: "BinaryArchive functions.data",
      containerId: "disk-group",
      x: 870,
      y: 434,
      width: 280,
      height: 70,
      renderStyle: "outline",
      labelLines: ["BinaryArchive", "functions.data"],
      fontSizeOverride: 17,
    },
    {
      id: "binary-note-1",
      label: "Shader / State",
      x: 108,
      y: 564,
      width: 324,
      height: 78,
      textRuns: [
        {text: "Shader / State", x: 18, y: 20, fontSize: 17, fontWeight: 820},
        {text: "内容一变，旧缓存就可能不再匹配。", x: 18, y: 43, fontSize: 14, fontWeight: 700},
        {text: "binary / cache 不是稳定接口。", x: 18, y: 61, fontSize: 13, fontWeight: 660},
      ],
    },
    {
      id: "binary-note-2",
      label: "codegen / 映射",
      x: 478,
      y: 564,
      width: 324,
      height: 78,
      textRuns: [
        {text: "codegen / 映射", x: 18, y: 20, fontSize: 17, fontWeight: 820},
        {text: "SharedCode / Hash / scl 一变，就要重建。", x: 18, y: 43, fontSize: 14, fontWeight: 700},
        {text: "旧 binary 只对应那次构建组合。", x: 18, y: 61, fontSize: 13, fontWeight: 660},
      ],
    },
    {
      id: "binary-note-3",
      label: "OS / Driver / GPU / API",
      x: 848,
      y: 564,
      width: 324,
      height: 78,
      textRuns: [
        {text: "OS / Driver / GPU / API", x: 18, y: 20, fontSize: 16, fontWeight: 820},
        {text: "环境一变，本地 binary 也可能立刻失效。", x: 18, y: 43, fontSize: 13.5, fontWeight: 700},
        {text: "它只是某次平台组合的落盘形态。", x: 18, y: 61, fontSize: 13, fontWeight: 660},
      ],
    },
    {
      id: "binary-archive2",
      label: "Metal Binary Archive 2 ?",
      x: 927,
      y: 648,
      width: 166,
      height: 44,
      textRuns: [
        {text: "Metal", x: 83, y: 13, fontSize: 12.5, fontWeight: 820, textAnchor: "middle"},
        {text: "Binary Archive 2 ?", x: 83, y: 29, fontSize: 14, fontWeight: 800, textAnchor: "middle"},
      ],
    },
  ],
  edges: [
    {
      id: "stable-to-gfx",
      from: {x: 432, y: MID_Y},
      to: {x: 478, y: MID_Y},
      tone: "primary",
      arrowEnd: true,
    },
    {
      id: "vertex-to-gpu",
      from: {x: 490, y: 78},
      to: {x: 582, y: 78},
      tone: "support",
      arrowEnd: true,
    },
    {
      id: "gpu-to-pixel",
      from: {x: 698, y: 78},
      to: {x: 790, y: 78},
      tone: "support",
      arrowEnd: true,
    },
    {
      id: "gfx-to-gpu",
      from: {x: 640, y: 164},
      to: {x: 640, y: 118},
      tone: "primary",
      arrowEnd: true,
    },
    {
      id: "gl-to-disk",
      from: {x: 780, y: 253},
      to: {x: 870, y: 253},
      tone: "proof",
      dashed: true,
      arrowEnd: true,
    },
    {
      id: "vk-to-disk",
      from: {x: 780, y: 361},
      to: {x: 870, y: 361},
      tone: "proof",
      dashed: true,
      arrowEnd: true,
    },
    {
      id: "metal-to-disk",
      from: {x: 780, y: 469},
      to: {x: 870, y: 469},
      tone: "proof",
      dashed: true,
      arrowEnd: true,
    },
  ],
};
